### PR TITLE
Adding classId to journal view + Gradle sync issue

### PR DESCRIPTION
**Pull request by cviali**
Added a simple solution to solve a problem listed on #40 to show the class code on journal's view.

Stuffs I've changed for this PR:
- Swapped positions on both jcenter() and google() on buildscript and allprojects to fix a Gradle sync issue.
- Added a TextView journalCode copied from journalCampus to view the classId.
- Added already existing classId from session to view by adding itemView on the adapter + tweaking the GSLC logic function to GONE the classId as well, little changes to the overall design.

### CODE REVIEW

**Comment by chrsep** [comment]
Hi @cviali,
Thanks a lot for the help man, i think the the class code is better placed in the beginning before the time though, so it's a bit more clear (classcode, time + location), maybe i'll add it later. I'll merge this now. Thanks 😁

**Comment by cviali** [comment]
Have you given the thoughts of actually implementing the Assignment feature? Since I saw you've created some starting files and a view for it in journal items' layout.

**Comment by chrsep** [comment]
I actually did, a long time ago. I was planning to make the journal items clickable and shows an icon or symbol if there is an assignment for the given class shift, and when it's clicked, it will show more detail about the class, like assignments, slide and attendance, but i wasn't able to complete it back then, so i disabled it 😂.

**Comment by cviali** [comment]
Ok.. I'll make the changes you'd recommend to the xml (classcode, time + location thing) pretty soon, should I create another PR from a new branch, per usual?

**Comment by chrsep** [comment]
Thx, don't worry about the the xml change, i've added it yesterday :smile:. I personally don't really like Binus's calendar design though. It feels like it can be done better.

The 1h40m thing never change right? it seems to just add noise to the layout, same with all the lines and brackets. I think course code doesn't need to be placed so big next to the name too, since it's usually not that important when scanning through the list right? I think it's important to just keep the most necessary things on screen to utilize the reduce clutter and maximize efficient use of screen space.

Usually when we open the journal in Portal, we want to know when a class starts, and where, so i feel it's better to put them close together so our eyes doesn't need to moves a lot when checking out the schedule, but here they put it on the opposite side of the screen. 

The dot that gets bigger when there is assignment doesn't really feels right for me too, seems like it doesn't provide enough contrast between having an assignment and not, like if you scroll really fast, there is a chance to miss the shift that have an assignment. I think it's better to add a separate symbol for assignment that disappears when there is no assignment.

I also feel that the dot is too small, compared to the current class type indicator, I feel it's nicer to have it so big on the right cause i usually scroll through the list to find the red GSLC class a lot :sweat_smile:, but this might be just my preference though.

The height though, in portal, do need an adjustment, it's a bit unbalanced to be honest. Maybe it can be a bit more dense.

You should create a feature request so that a lot more people can see and give feedback.

**Pull request merged**
