### PR TITLE
Resource multiple course type support

### PR DESCRIPTION
**Pull request by senacand**
A simple (albeit a bit dirty UI wise, but usable) to solve the problem mentioned on #44 
The tabs in Resources tab no longer only show one per course name, but instead show all of them. This allows the user to get resources of different course types (LEC, LAB, TUT, etc.) of the same course.

What I did in this PR:
- Merged with develop (I made this branch from the `master` branch instead of `develop`, so I ended up having to merge develop into this branch)
- Changed the order of repository (google and jcenter) due to Gradle sync issues
- Added the functionality above

### CODE REVIEW

**Comment by cviali** [comment]
I've started to get the hang of pulling data from binusmaya and showing them on views, I would like to make a PR my simple layout changes here to see if you guys like it.

**Comment by senacand** [comment]
@cviali I'm not the maintainer of this repo, but you can read the Contributing part of README.md for the instruction.

**Comment by cviali** [comment]
> 
> 
> @cviali I'm not the maintainer of this repo, but you can read the Contributing part of README.md for the instruction.

Kind of a noob question.. How do I commit to my forked repo without making unintended, additional changes to other files? i.e. the files in .idea folders. I've read some posts that suggest adding those locations to .gitignore, but it's already there and GitHub Desktop kept showing those changes and will add them alongside my changes to my forked repo if I tried to push it.

here's the screen snippet of my Desktop app: [screenshot](https://puu.sh/CbkAi/56436e647f.PNG)

**Comment by senacand** [comment]
> Kind of a noob question.. How do I commit to my forked repo without making unintended, additional changes to other files? i.e. the files in .idea folders. I've read some posts that suggest adding those locations to .gitignore, but it's already there and GitHub Desktop kept showing those changes and will add them alongside my changes to my forked repo if I tried to push it.

@cviali With `.gitignore` already there, it should've not been pushed. If it still does, just choose the files that you change manually instead of pushing all changes.

**Comment by chrsep** [comment]
Hi @senacand 
Sorry for taking so long to respond, haven't got much free time lately. Thx a lot man, it works nicely, i'll merge this now.

**Pull request merged**
